/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.AddressInfo;
import Business.CheckingInfo;
import Business.DLicenseInfo;
import Business.Demographic;
import Business.SavingInfo;
import Business.medicalRecord;

/**
 *
 * @author krish
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form DemographicJFrame
     */Demographic demographic;
       AddressInfo address;
       CheckingInfo checking;
       DLicenseInfo license;
       SavingInfo saving;
       medicalRecord medical;
       ReportPanel report;
    public MainJFrame() {
        initComponents();
        demographic = new Demographic();
        address = new AddressInfo();
        checking = new CheckingInfo();
        license = new DLicenseInfo();
        saving = new SavingInfo();
        medical = new medicalRecord();
//        report = new ReportPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Splitpane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        addDemoDataBtn = new javax.swing.JButton();
        viewDemoBtn = new javax.swing.JButton();
        addAddressBtn = new javax.swing.JButton();
        viewAddressBtn = new javax.swing.JButton();
        addSavingsBtn = new javax.swing.JButton();
        viewSavingsBtn = new javax.swing.JButton();
        addDlicenseBtn = new javax.swing.JButton();
        viewDlicenseBtn = new javax.swing.JButton();
        addMedicalBtn = new javax.swing.JButton();
        viewMedicalBtn = new javax.swing.JButton();
        addCheckingBtn = new javax.swing.JButton();
        viewCheckingBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addDemoDataBtn.setText("Add Demographic Data");
        addDemoDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDemoDataBtnActionPerformed(evt);
            }
        });

        viewDemoBtn.setText("View Demographic Data");
        viewDemoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDemoBtnActionPerformed(evt);
            }
        });

        addAddressBtn.setText("Add Address Info");
        addAddressBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAddressBtnActionPerformed(evt);
            }
        });

        viewAddressBtn.setText("View Address Info");
        viewAddressBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAddressBtnActionPerformed(evt);
            }
        });

        addSavingsBtn.setText("Add Savings Account Info");
        addSavingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSavingsBtnActionPerformed(evt);
            }
        });

        viewSavingsBtn.setText("View Savings Account Info");
        viewSavingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSavingsBtnActionPerformed(evt);
            }
        });

        addDlicenseBtn.setText("Add Driver's License Info");
        addDlicenseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDlicenseBtnActionPerformed(evt);
            }
        });

        viewDlicenseBtn.setText("View Driver's Licesnse Info");
        viewDlicenseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDlicenseBtnActionPerformed(evt);
            }
        });

        addMedicalBtn.setText("Add Medical Record");
        addMedicalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMedicalBtnActionPerformed(evt);
            }
        });

        viewMedicalBtn.setText("View Medical Record");
        viewMedicalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMedicalBtnActionPerformed(evt);
            }
        });

        addCheckingBtn.setText("Add Checking Account Info");
        addCheckingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCheckingBtnActionPerformed(evt);
            }
        });

        viewCheckingBtn.setText("View Checking Account Info");
        viewCheckingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCheckingBtnActionPerformed(evt);
            }
        });

        jButton1.setText("See Detailed Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addDemoDataBtn)
                    .addComponent(viewDemoBtn)
                    .addComponent(addAddressBtn)
                    .addComponent(viewAddressBtn)
                    .addComponent(addSavingsBtn)
                    .addComponent(viewSavingsBtn)
                    .addComponent(addDlicenseBtn)
                    .addComponent(viewDlicenseBtn)
                    .addComponent(addMedicalBtn)
                    .addComponent(viewMedicalBtn)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(viewCheckingBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addCheckingBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton1))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(addDemoDataBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewDemoBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addAddressBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewAddressBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addSavingsBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewSavingsBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addCheckingBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewCheckingBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addDlicenseBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewDlicenseBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addMedicalBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewMedicalBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        Splitpane.setLeftComponent(jPanel1);

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel1.setText("Personal Info Database");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(406, Short.MAX_VALUE))
        );

        Splitpane.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Splitpane, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Splitpane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addAddressBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAddressBtnActionPerformed
        // TODO add your handling code here:
        addAddressPanel addresspanel = new addAddressPanel(address);
        Splitpane.setRightComponent(addresspanel);
    }//GEN-LAST:event_addAddressBtnActionPerformed

    private void viewAddressBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAddressBtnActionPerformed
        // TODO add your handling code here:
        viewAddressPanel viewaddresspanel = new viewAddressPanel(address);
        Splitpane.setRightComponent(viewaddresspanel);
    }//GEN-LAST:event_viewAddressBtnActionPerformed

    private void addCheckingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCheckingBtnActionPerformed
        // TODO add your handling code here:
        addCheckingPanel checkingpanel = new addCheckingPanel(checking);
        Splitpane.setRightComponent(checkingpanel);
        
    }//GEN-LAST:event_addCheckingBtnActionPerformed

    private void viewCheckingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCheckingBtnActionPerformed
        // TODO add your handling code here:
        viewCheckingPanel viewcheckingpanel = new viewCheckingPanel(checking);
        Splitpane.setRightComponent(viewcheckingpanel);
    }//GEN-LAST:event_viewCheckingBtnActionPerformed

    private void addDlicenseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDlicenseBtnActionPerformed
        // TODO add your handling code here:
        addLicensePanel licensepanel = new addLicensePanel(license);
        Splitpane.setRightComponent(licensepanel);
        
    }//GEN-LAST:event_addDlicenseBtnActionPerformed

    private void viewDlicenseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDlicenseBtnActionPerformed
        // TODO add your handling code here:
        viewLicensePanel viewlicensepanel = new viewLicensePanel(license);
        Splitpane.setRightComponent(viewlicensepanel);
        
    }//GEN-LAST:event_viewDlicenseBtnActionPerformed

    private void addDemoDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDemoDataBtnActionPerformed
        // TODO add your handling code here
        addDemoPanel demopanel = new addDemoPanel(demographic);
        Splitpane.setRightComponent(demopanel);
        
    }//GEN-LAST:event_addDemoDataBtnActionPerformed

    private void viewDemoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDemoBtnActionPerformed
        // TODO add your handling code here:
        viewDemoPanel viewdemopanel = new viewDemoPanel(demographic);
        Splitpane.setRightComponent(viewdemopanel);
    }//GEN-LAST:event_viewDemoBtnActionPerformed

    private void addSavingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSavingsBtnActionPerformed
        // TODO add your handling code here:
        addSavingPanel savingpanel = new addSavingPanel(saving);
        Splitpane.setRightComponent(savingpanel);
    }//GEN-LAST:event_addSavingsBtnActionPerformed

    private void viewSavingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSavingsBtnActionPerformed
        // TODO add your handling code here:
        viewSavingPanel viewsavingpanel = new viewSavingPanel(saving);
        Splitpane.setRightComponent(viewsavingpanel);
    }//GEN-LAST:event_viewSavingsBtnActionPerformed

    private void addMedicalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMedicalBtnActionPerformed
        // TODO add your handling code here:
        addMedicalRecord medicalrecord = new addMedicalRecord(medical);
        Splitpane.setRightComponent(medicalrecord);
    }//GEN-LAST:event_addMedicalBtnActionPerformed

    private void viewMedicalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMedicalBtnActionPerformed
        // TODO add your handling code here:
        viewMedicalRecord viewmedical = new viewMedicalRecord(medical);
        Splitpane.setRightComponent(viewmedical);
    }//GEN-LAST:event_viewMedicalBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ReportPanel reportpanel = new ReportPanel(address, checking, license, demographic, saving, medical);
        Splitpane.setRightComponent(reportpanel);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane Splitpane;
    private javax.swing.JButton addAddressBtn;
    private javax.swing.JButton addCheckingBtn;
    private javax.swing.JButton addDemoDataBtn;
    private javax.swing.JButton addDlicenseBtn;
    private javax.swing.JButton addMedicalBtn;
    private javax.swing.JButton addSavingsBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton viewAddressBtn;
    private javax.swing.JButton viewCheckingBtn;
    private javax.swing.JButton viewDemoBtn;
    private javax.swing.JButton viewDlicenseBtn;
    private javax.swing.JButton viewMedicalBtn;
    private javax.swing.JButton viewSavingsBtn;
    // End of variables declaration//GEN-END:variables
}
